apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-storage-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
  namespace: openshift-machine-api
status:
  readyReplicas: 1
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-storage-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}b'
  namespace: openshift-machine-api
status:
  readyReplicas: 1
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-storage-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}c'
  namespace: openshift-machine-api
status:
  readyReplicas: 1
