apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-openshift-dr-clusters
  namespace: rhacm-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: cluster.open-cluster-management.io/clusterset=openshift-dr, operator: In, values: ["openshift-dr"]}
          - {key: name, operator: NotIn, values: ["local-cluster"]}
