apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-dr-cluster
placementBindingDefaults:
  name: binding-policy-openshift-dr-hub
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: rhacm-policies
  policySets:
    - openshift-dr-hub
  remediationAction: inform
  severity: medium
  standards:
    - NIST SP 800-53
policies:

- name: policy-ingress-cert
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-ingress-cert/policy-ingress-certificate.yaml
  policySets:
    - openshift-dr-clusters
  remediationAction: enforce


- name: policy-broker
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-submariner/policy-broker.yaml
  policySets:
    - openshift-dr-hub
  remediationAction: enforce


- name: policy-managedclusteraddon
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-submariner/policy-managedclusteraddon.yaml
  remediationAction: inform
  policySets:
    - openshift-dr-hub

- name: policy-managedclusteraddon-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-submariner/policy-managedclusteraddon-status.yaml
  remediationAction: inform
  policySets:
    - openshift-dr-clusters

- name: policy-odf-globalnet
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odfmo/policy-odf-globalnet.yaml
  policySets:
    - openshift-dr-clusters
  remediationAction: enforce
  dependencies:
  - name: policy-managedclusteraddon-status
  - name: policy-ingress-cert

- name: policy-odfmo
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odfmo/policy-odf-multicluster-orchestrator.yaml
  remediationAction: enforce
  policySets:
    - openshift-dr-hub
  dependencies: 
  - name: policy-managedclusteraddon

- name: policy-odfmo-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odfmo/policy-odf-multicluster-orchestrator-status.yaml
  remediationAction: inform
  policySets:
    - openshift-dr-hub
  dependencies:
  - name: policy-odfmo


- name: policy-drpolicy
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odfmo/policy-drpolicy.yaml
  remediationAction: enforce
  policySets:
    - openshift-dr-hub
  dependencies:
  - name: policy-odfmo-status

- name: policy-mirrorpeer
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odfmo/policy-mirrorpeer.yaml
  remediationAction: enforce
  policySets:
    - openshift-dr-hub
  dependencies:
  - name: policy-odfmo-status

- name: policy-drpolicy-status
  categories:
    - SI System and Information Integrity
  controls:
    - SI-7 Software Firmware and Information Integrity
  manifests:
    - path: input-odfmo/policy-drpolicy-status.yaml
  remediationAction: inform
  policySets:
    - openshift-dr-hub
  dependencies:
  - name: policy-drpolicy


policySets:
  - description: The OpenShift DR policy set applies policies that will configure
      Submariner and ODF Regional DR. This policy set is focused on
      the components that install to the Advanced Cluster Management hub.
    name: openshift-dr-hub
    placement:
      placementPath: input/hub-placement.yaml
  - description: The OpenShift DR policy set applies policies that will configure
      Submariner and ODF Regional DR. This policy set is focused on
      the components that install to the clusters participating in the DR configuration
    name: openshift-dr-clusters
    placement:
      placementPath: input/clusters-placement.yaml
