apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: install-submariner-addon
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    {{- $clusters := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "" "cluster.open-cluster-management.io/clusterset=openshift-dr").items }}
    {{- range $cluster := $clusters }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: addon.open-cluster-management.io/v1alpha1
        kind: ManagedClusterAddOn
        metadata:
          name: submariner
          namespace: '{{ $cluster }}'
        spec:
          installNamespace: submariner-operator
    {{- end }}
