apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
     name: submariner
     namespace: '{{ .ManagedClusterName }}'
spec:
     installNamespace: submariner-operator
