apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: install-submariner-addon-status
spec:
  remediationAction: inform
  severity: low
  object-templates-raw: |
    - complianceType: musthave
      objectDefinition:
        apiVersion: submariner.io/v1alpha1
        kind: Submariner
        metadata:
          name: submariner
          namespace: submariner-operator
        status:
          gateways:
          - connections:
            - endpoint:
              status: connected
