apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
     name: submariner
     namespace: '{{hub .ManagedClusterName hub}}'
spec:
     installNamespace: submariner-operator
