apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: configure-ingress-certificate
spec:
  remediationAction: enforce
  severity: low
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ingress-cert
        namespace: openshift-ingress
      data:
        tls.crt: '{{hub fromSecret "rhacm-policies" (printf "%s-ingress-cert" .ManagedClusterName) "tls.crt" hub}}'
        tls.key: '{{hub fromSecret "rhacm-policies" (printf "%s-ingress-cert" .ManagedClusterName) "tls.key" hub}}'
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: ingress-cert  
