apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: install-multicluster-orchestrator-operator-status
spec:
  remediationAction: inform
  severity: low
  object-templates: 
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: odf-multicluster-orchestrator
          namespace: openshift-operators
        status:
          state: AtLeastKnown