apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: configure-drpolicy
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    {{- $clusters := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "" "cluster.open-cluster-management.io/clusterset=openshift-dr").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: ramendr.openshift.io/v1alpha1
        kind: DRPolicy
        metadata:
          name: '{{ index ($cluster.metadata.name).items 0  }}-5m'
        spec:
          drClusters:
          - ocp1
          - ocp2
          schedulingInterval: 5m
