apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/odf-multicluster-orchestrator.openshift-operators: ''
  name: odf-multicluster-orchestrator
  namespace: openshift-operators
spec:
  #channel: stable-4.13
  installPlanApproval: Automatic
  name: odf-multicluster-orchestrator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: odf-multicluster-orchestrator.v4.13.4-rhodf
