apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/odf-multicluster-orchestrator.openshift-operators: ''
  name: odf-multicluster-orchestrator
  namespace: openshift-operators
spec:
  #channel: stable-4.13
  installPlanApproval: Automatic
  name: odf-multicluster-orchestrator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: odf-multicluster-orchestrator.v4.13.4-rhodf
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: enable-odfmo-plugin
spec:
  remediationAction: enforce
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        kind: Console
        apiVersion: operator.openshift.io/v1
        metadata:
          name: cluster
        spec:
          plugins: [
            "odf-multicluster-console"
          ] 

