apiVersion: v1
kind: Namespace
metadata:
  name: app1
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: v1
kind: Namespace
metadata:
  name: app2
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
