apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: baseline-configuration-policies
  namespace: rhacm-applications
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - baseline-configuration-policies
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-vagnerfarias-rhacm-examples-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: ggithubcom-vagnerfarias-rhacm-examples
  namespace: ggithubcom-vagnerfarias-rhacm-examples-ns
spec:
  type: Git
  pathname: 'https://github.com/vagnerfarias/rhacm-examples.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: policies
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: baseline-configuration-policies
  name: baseline-configuration-policies-subscription-1
  namespace: rhacm-applications
spec:
  channel: ggithubcom-vagnerfarias-rhacm-examples-ns/ggithubcom-vagnerfarias-rhacm-examples
  placement:
    placementRef:
      kind: PlacementRule
      name: baseline-configuration-policies-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: baseline-configuration-policies
  name: baseline-configuration-policies-placement-1
  namespace: rhacm-applications
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
