# This policy creates 1 OpenShift MachineSet to be used as an infrastructure node
#
# This policy contains an Amazon Machine Identifier which must be updated in the policy.  Obtain the AMI id from: 
# https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/installing/installing-on-aws#installation-aws-ami-stream-metadata_installing-aws-user-infra
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-infra-machinesets
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: machineset-infra1
        spec:
          severity: high
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: machine.openshift.io/v1beta1
              kind: MachineSet
              metadata:
                labels:
                  machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                  machine.openshift.io/cluster-api-machine-role: infra
                  machine.openshift.io/cluster-api-machine-type: infra
                name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-infra-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
                namespace: openshift-machine-api
              spec:
                replicas: '{{hub fromConfigMap  "rhacm-policies" "policy-infra-machineset-config" "replicas-a" | toInt hub}}'
                selector:
                  matchLabels:
                    machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                    machine.openshift.io/cluster-api-machineset: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-infra-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
                template:
                  metadata:
                    labels:
                      machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                      machine.openshift.io/cluster-api-machine-role: infra
                      machine.openshift.io/cluster-api-machine-type: infra
                      machine.openshift.io/cluster-api-machineset: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-infra-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
                  spec:
                    metadata:
                      labels:
                        node-role.kubernetes.io/worker: ""
                    providerSpec:
                      value:
                        ami:
                          id: ami-0ccb85644951df8b3
                        apiVersion: awsproviderconfig.openshift.io/v1beta1
                        blockDevices:
                        - ebs:
                            iops: 0
                            volumeSize: 120
                            volumeType: gp2
                        credentialsSecret:
                          name: aws-cloud-credentials
                        deviceIndex: 0
                        iamInstanceProfile:
                          id: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-worker-profile'
                        instanceType: m5.xlarge
                        kind: AWSMachineProviderConfig
                        metadata:
                          creationTimestamp: null
                        placement:
                          availabilityZone: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
                          region: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}'
                        publicIp: null
                        securityGroups:
                        - filters:
                          - name: tag:Name
                            values:
                            - '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-worker-sg'
                        subnet:
                          filters:
                          - name: tag:Name
                            values:
                            - '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-private-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
                        tags:
                        - name: 'kubernetes.io/cluster/{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                          value: owned
                        userDataSecret:
                          name: worker-user-data
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: machineset-infra1-status
        spec:
          remediationAction: inform
          severity: low
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: machine.openshift.io/v1beta1
              kind: MachineSet
              metadata:
                #labels:
                #  machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                #  machine.openshift.io/cluster-api-machine-role: infra
                #  machine.openshift.io/cluster-api-machine-type: infra
                name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-infra-{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}a'
                namespace: openshift-machine-api
              status:
                readyReplicas: '{{hub fromConfigMap  "rhacm-policies" "policy-infra-machineset-config" "replicas-a" | toInt hub}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-infra-machinesets
  namespace: rhacm-policies
placementRef:
  name: placement-policy-infra-machinesets
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-infra-machinesets
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-infra-machinesets
  namespace: rhacm-policies
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - ocp1
          - ocp2

